before_script:
- apt-get install pandoc
script: make -j 4
deploy:
  api_key:
    secure: QLbozoGQTgYJ+7v+E6EULS330OROhuS+Y9E8s8kSEQq2SE6HkTKO/o8HtrRukwZ+fFA0VuBgq4N/6WUzTybuXEJQw/Mau/X5Jzln5qovWG5ooOwZFspg5xFxR6IrKXT+vkCjLfCqRmMf7cLVgvwi8QNNsi5wlHABpEp6dmrsA6lFhFbK3qF3y6oWiLmAGzUZRTZphE+aPwzKp+IRuyDaczUVo1CWpvhPpvJyUcV+qCjtQFXRSaNUa5JELs3vmyZ97UzJ+8djcIPG7zsziEgldf+pGlIGuXEfS8V1TJRVWqqx47AWKiWGXwk+Jglw6srSUTGy7e5lXhiALyWeDgFs2ptTYA17fEi7OQQ+/ICIMqiiMhP/h661aB0dx8rqdzZwur6HbO4X4/dYNJMjz1xg9hw8ytYWL+O6ajIKwuWasyw5GaQ5wg1RfYcXq14laRSFEAgEVXUIlzWeeg3aOkkreqAM/pVY0MBXVmsnJnot5FC5fBLW4ZBD0DOeuwjFZ4wrDs/g161aJBfxP9VrORmnccvMeCQdFRjXK+AnYvBYLaJusVyMuPqyccJ0DDX97Uyy55N6Eun2yodBnUj/ZQtQNPOAj85ZFOocyXh7MjZgK9jT2Ualj+VGGkGBI/VeldQpHGDUYLhje9UN0Mqy5EqrjEBFQfrs8idOx5T/dH4h+Sw=
